services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - project_network

  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - project_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  dbgate:
    image: dbgate/dbgate
    restart: unless-stopped
    networks:
      - project_network
    ports:
      - 3000:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      BASIC_AUTH: true
      LOGINS: admin
      LOGIN_PASSWORD_admin: admin
      CONNECTIONS: con1
      LABEL_con1: MongoDB
      URL_con1: mongodb://root:example@mongo:27017/
      ENGINE_con1: mongo@dbgate-plugin-mongo

networks:
  project_network:
    driver: bridge

volumes:
  mongodata:
    external: true
  dbgate-data:
    external: true