version: "3.9"
services:
  web:
    build: .
    ports:
      - "8380:8080"
    networks:
      - project_network

  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - project_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8381:8081"
    networks:
      - project_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
networks:
  project_network:
    driver: bridge

volumes:
  mongodata:
    external: true